### ISSUE TITLE
Problems installing 4.0.0 in Windows 10

### ISSUE THREAD

**Issue by reaseno** [rawnly/splash-cli#111]
Since 3.4.15 can apparently no longer load a picture of the day, I looked in github for build entries. There, I only happened to see at third glance that there is already a final release of version 4:
https://github.com/rawnly/splash-cli/releases/tag/v4.0.0

However, there are new alpha versions of 4 after that. A bit confusing. Why is this not latest?

Then I tried to install it in Win10 as follows:
npm install splash-cli@next -g

Then I get the following error message:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for splash-cli@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm --version
9.8.0

**Comment by rawnly** [comment]
hi thanks for reporting, sorry for the delay but i’m out for summer, i’ll be back on monday and i’ll try to fix this. (v4.x is still wip)

**Comment by rawnly** [comment]
Ok, after viewing releases seems like it has been a mistake. v4 hasn't been tested on windows yet. 
I just deleted the tag you linked. You can install the latest via npm but the `next` tag is not working yet. I'm figuring out a way to publish a go package on npm to make it easier to install for everyone and make the transition smoother

**Comment by rawnly** [comment]
Feel free to re-open this issue if you need further infos
