### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by skurilyak** [Rawnly/splash-cli#14]
### Basic informations
- **splash-cli** version: `2.3.5`
- NodeJs version: `6.10.0`
- Your OS: **macOS Sierra, 10.12.3 (16D32)**

# ISSUE
When I run `$ splash` I get the following error:

```
env: node\r: No such file or directory
```

**Comment by skurilyak** [comment]
I fixed the problem by typing:
```
$ brew uninstall dos2unix
$ brew install dos2unix
$ find /usr/local/lib/node_modules/splash-cli -name "*.js" | xargs sudo dos2unix
```

Referencing the following [StackOverflow Issue](http://stackoverflow.com/a/31041038/2289214)

**Comment by Rawnly** [comment]
thanks @skurilyak i'll add this to known issues in readme!
