### ISSUE TITLE
splash not downloading image

### ISSUE THREAD

**Issue by AlecRust** [Rawnly/splash-cli#16]
### Basic informations
- **splash-cli** version: `2.3.9`
- NodeJs version: `v7.7.2`
- Your OS: **macOS 10.12.4**

# ISSUE
When I run `splash` no image is downloaded and stored at this location:

![screenshot](https://i.imgur.com/QeoTvxm.png)

**Comment by Rawnly** [comment]
> When I run splash no image is downloaded and stored at this location:

Please try with the `--progress` flag and post the screenshot.

Splash hasn't been tested with note `7.7.2`

**Comment by Rawnly** [comment]
@AlecRust Please can you try to install [`simple-splash-cli`](simple) and download an image? Does it works?

[simple]: https://github.com/rawnly/simple

**Comment by AlecRust** [comment]
@Rawnly not sure on the usage of that tool - how do I run it?

`simple --config get config` produces:

![screenshot](https://i.imgur.com/e7G1Zbu.png)

**Comment by Rawnly** [comment]
Oh sorry the readme is not "perfect". You should run `simple [photo_id]` to check if the problem is a connection problem as #9  or a "code problem"

**Comment by AlecRust** [comment]
Yup that worked:

![screenshot](https://i.imgur.com/hSaqHOX.png)

Photo is present in that location.

**Comment by Rawnly** [comment]
> Yup that worked:
> 
> 
> 
> Photo is present in that location.

Ok try to run `splash save`

**Comment by AlecRust** [comment]
Same error unfortunately:

![screenshot](https://i.imgur.com/tZ7hJqa.png)

**Comment by Rawnly** [comment]
try to manually create it

**Comment by AlecRust** [comment]
Yup, after manually creating the `/splash_photos` directory it works:

![screenshot](https://i.imgur.com/t30jkSL.png)

**Comment by Rawnly** [comment]
Ok i'll fix it, maybe it doesn't create the folder. Thanks for reporting
