### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by AlecRust** [Rawnly/splash-cli#17]
### Basic informations
- **splash-cli** version: `2.3.9`
- NodeJs version: `v7.7.2`
- Your OS: **macOS 10.12.4**

# ISSUE
When I run `splash` only the main monitor has its wallpaper changed. Can splash-cli also set the wallpaper of additional monitors if they are present?

**Comment by Rawnly** [comment]
Sorry but this is not a `splash` feature but is about the `wallpaper` module.

See [#1](https://github.com/sindresorhus/wallpaper-cli/issues/1)

**Comment by Rawnly** [comment]
I'm working on an update. Soon available

> This is supported now in v2.0

**Comment by Rawnly** [comment]
Fixed on [`35c5385`](https://github.com/splash-cli/splash-cli/commit/35c538570376c96f55676f5ec1a8a5aae015f601)
