### ISSUE TITLE
JS error when running splash

### ISSUE THREAD

**Issue by AlecRust** [Rawnly/splash-cli#18]
### Basic informations
- **splash-cli** version: `2.5.1`
- NodeJs version: `v8.1.2`
- Your OS: **macOS**

# ISSUE
When running `splash` I get the following error:

![screenshot](https://i.imgur.com/6ez92n2.png)

**Comment by Rawnly** [comment]
Are you under any proxy? It seems it can't connect to the host

**Comment by Rawnly** [comment]
It was a problem with archivments function, now in 2.5.2 should be fixed. Try updating with `splash update`

**Comment by AlecRust** [comment]
That doesn't seem to work, actually I don't seem to be able to get the new version:

![screenshot](https://i.imgur.com/qHNoBBi.png)

**Comment by Rawnly** [comment]
Try npm i -g splash-cli

Federico Vitale

Il 5 lug 2017, 11:07 +0200, Alec Rust <notifications@github.com>, ha scritto:

**Comment by AlecRust** [comment]
Nope:

![screenshot](https://i.imgur.com/ivjBrDS.png)

**Comment by Rawnly** [comment]
Oh sorry there was a problem with the publish. I'm fixing it

**Comment by Rawnly** [comment]
OK i've fixed that. please try now to update (or with npm/yarn or via splash-cli)

**Comment by AlecRust** [comment]
Upgrading with `npm i -g splash-cli` worked (`splash update` didn't).

Can confirm this problem doesn't exist on the new 2.5.2, many thanks!
