### ISSUE TITLE
Errors runnings help command after install 

### ISSUE THREAD

**Issue by ChavaSobreyra** [Rawnly/splash-cli#6]
### Basic informations
- **splash-cli** version: `2.3`
- NodeJs version: `7.6`
- Your OS: **MacOS**

# ISSUE

    /usr/local/bin/splash: line 1: use strict: command not found
    /usr/local/bin/splash: line 2: //: is a directory
    /usr/local/bin/splash: line 3: syntax error near unexpected token `'chili-js''
    /usr/local/bin/splash: line 3: `require('chili-js');'

**Comment by rjcoupe** [comment]
This occurs when running `splash` alone, as well.

Node 4.5, other details the same.

**Comment by kpollich** [comment]
I'm encountering the same issue running Node 7.6.0 on macOS

```
/Users/kylepollich/.nvm/versions/node/v7.6.0/bin/splash: line 1: use strict: command not found
/Users/kylepollich/.nvm/versions/node/v7.6.0/bin/splash: line 2: //: is a directory
/Users/kylepollich/.nvm/versions/node/v7.6.0/bin/splash: line 3: syntax error near unexpected token `'chili-js''
/Users/kylepollich/.nvm/versions/node/v7.6.0/bin/splash: line 3: `require('chili-js');'
```

**Comment by cqcwillard** [comment]
The problem is stemming from node_modules/splash-cli/cli.js

It needs this line at the top of the file since it's executing as a command and not a node application.
`#!/usr/bin/env node`

**Comment by cqcwillard** [comment]
I also had to run mkdir ~/Pictures/splash_photos.  I'll submit a PR for the initial issue.

**Comment by FredrikAugust** [comment]
Well, I added use strict to the top of cli.js, but then it will complain about another file from another library. Ubuntu 16.04
